### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by IonicSyz1823** [Muqsit/Tebex#19]
I'm just wondering but is this tebex plugin a forked from the original tebex plugin that can be downloaded from the tebex site? Since Tebex keeps track and collect details so they can use it when people chargeback from the store

**Comment by Muqsit** [comment]
Tebex stopped maintaining their plugin about 3 years back and it's riddled with bugs and security issues. So this plugin is  completely different from Tebex's work.

> Since Tebex keeps track and collect details so they can use it when people chargeback from the store

I'm not sure what the state of non "Tebex Checkout" accounts are but ever since Tebex Checkout, they've been providing an insurance like service where they take a ≈5% cut from every payment in return for never losing cash from chargebacks.
