### ISSUE TITLE
Plugin Crash - PM - API 4.14.0

### ISSUE THREAD

**Issue by NJMD13** [Muqsit/Tebex#22]
Hello, the plugin gives me an error, I really don't know much about plugins.
Here I leave a file generated in crashdumps of my server.

Pocketmine version: 4.14.0
Minecraft Version: 1.19.60

[Mon_Feb_13-05.54.40-CST_2023.log](https://github.com/Muqsit/Tebex/files/10721955/Mon_Feb_13-05.54.40-CST_2023.log)

**Comment by Muqsit** [comment]
If you are running the plugin from source or have compiled the plugin manually, you must inject the [`TebexAPI`](https://github.com/Muqsit/TebexAPI) virion to ensure libraries are properly compiled together.

Alternatively, you can install the pre-compiled phar from poggit directly. Since poggit is down for the moment, you may use the phar linked with release v0.1.3: https://github.com/Muqsit/Tebex/releases/tag/0.1.3

**Comment by NJMD13** [comment]
Thanks a lot 💯
